const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {prepare,install}=require('../core/setup.cjs');const {ACTION_ID,authHash}=require('../core/bridge.cjs');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shoutout-setup-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(path.join(dir,'data'));const exe=path.join(dir,'Streamer.bot.exe');fs.writeFileSync(exe,'test');const actions={version:24,groups:['Existing'],actions:[{id:'existing',name:'Do not change',triggers:[{foo:'bar'}]}]};const settings={websockets:{address:'127.0.0.1',port:8080,endpoint:'/',autoStart:false,enableAuth:false,connections:[{keep:true}]},unrelated:{keep:true}};fs.writeFileSync(path.join(dir,'data','actions.json'),JSON.stringify(actions));fs.writeFileSync(path.join(dir,'data','settings.json'),JSON.stringify(settings));return {dir,exe,actions,settings};}
test('installer preserves existing actions and connection settings',t=>{const f=fixture(t),plan=prepare(f.exe,'secret=__BRIDGE_SECRET__','a'.repeat(64));assert.deepEqual(plan.actions.actions[0],f.actions.actions[0]);assert.equal(plan.actions.actions[1].id,ACTION_ID);assert.equal(plan.settings.websockets.autoStart,true);assert.deepEqual(plan.settings.websockets.connections,f.settings.websockets.connections);assert.equal(plan.settings.websockets.enableAuth,false);assert.deepEqual(plan.settings.unrelated,f.settings.unrelated);});
test('writes backups and is idempotent',async t=>{const f=fixture(t);const first=await install(f.exe,'__BRIDGE_SECRET__','a'.repeat(64),{checkRunning:async()=>[]});assert.ok(fs.existsSync(path.join(first.backup,'actions.json')));const second=prepare(f.exe,'__BRIDGE_SECRET__','a'.repeat(64));assert.equal(second.actions.actions.filter(a=>a.id===ACTION_ID).length,1);});
test('never edits or stops a running Streamer.bot',async t=>{const f=fixture(t),before=fs.readFileSync(path.join(f.dir,'data','actions.json'),'utf8');assert.deepEqual(await install(f.exe,'x','a'.repeat(64),{checkRunning:async()=>[f.exe]}),{needsClose:true});assert.equal(fs.readFileSync(path.join(f.dir,'data','actions.json'),'utf8'),before);});
test('unknown schema and public WebSocket bindings fail closed',t=>{const f=fixture(t);f.settings.websockets.address='0.0.0.0';fs.writeFileSync(path.join(f.dir,'data','settings.json'),JSON.stringify(f.settings));assert.throws(()=>prepare(f.exe,'x'));f.settings.websockets.address='127.0.0.1';fs.writeFileSync(path.join(f.dir,'data','settings.json'),JSON.stringify(f.settings));f.actions.version=999;fs.writeFileSync(path.join(f.dir,'data','actions.json'),JSON.stringify(f.actions));assert.throws(()=>prepare(f.exe,'x'));});
test('authentication implements SHA256 challenge exchange',()=>{assert.equal(authHash('test',{salt:'salt',challenge:'challenge'}),'e8+6Scly80/OsQGEYK6+RY6JrukPbvA3qve+QIjpdno=');});
